/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus')['ElAlert']
    ElButton: typeof import('element-plus')['ElButton']
    ElCard: typeof import('element-plus')['ElCard']
    ElCol: typeof import('element-plus')['ElCol']
    ElContainer: typeof import('element-plus')['ElContainer']
    ElDivider: typeof import('element-plus')['ElDivider']
    ElForm: typeof import('element-plus')['ElForm']
    ElFormItem: typeof import('element-plus')['ElFormItem']
    ElHeader: typeof import('element-plus')['ElHeader']
    ElInput: typeof import('element-plus')['ElInput']
    ElInputNumber: typeof import('element-plus')['ElInputNumber']
    ElMain: typeof import('element-plus')['ElMain']
    ElMenu: typeof import('element-plus')['ElMenu']
    ElMenuItem: typeof import('element-plus')['ElMenuItem']
    ElNotification: typeof import('element-plus')['ElNotification']
    ElOption: typeof import('element-plus')['ElOption']
    ElRow: typeof import('element-plus')['ElRow']
    ElSection: typeof import('element-plus')['ElSection']
    ElSelect: typeof import('element-plus')['ElSelect']
    ElTable: typeof import('element-plus')['ElTable']
    ElTableColumn: typeof import('element-plus')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
